version: '3'
services:
  dash-app:
    build: .
    ports:
      - "8000:8000"
    command: python app.py

  quotes-publisher:
    build: .
    ports:
      - "5000:5000"
    command: python quotes_publisher.py
